global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"

scrape_configs:
  # Monitor Prometheus sendiri
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Monitor Spring Boot Backend
  - job_name: 'spring-boot-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['sapi-service:8081']
    scrape_interval: 10s

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.100.9:9100']   # ganti sesuai IP/hostname Linux host
